### ISSUE TITLE
运行在docker上之后，如果触发了验证码就卡死

### ISSUE THREAD

**Issue by Asuka-Liu** [Wodlie/AutoMihoyoBBS#2]
![image](https://user-images.githubusercontent.com/29790075/224469846-d1a043d4-a727-447b-9a39-eeecd365977b.png)
日志如上，如果触发验证码后，程序就停止运行了，不会在定时启动

**Comment by Wodlie** [comment]
这个工具是要求自己手动解决验证码的
如果要完全自动化请使用原作者的(https://github.com/Womsxd/MihoyoBBSTools)
